[project]
name = "Allen's Django Tools"
version = "0.1.0"
description = "A set of tools for easier Django-development"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.6",
]
